services:
  - type: web
    name: dart-scorer-frontend
    runtime: docker
    branch: with-backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: API_BASE_URL
        sync: false
